import { useEffect, useState } from 'react';
import axios from 'axios';
import {
  MapPin, Building, Star, RefreshCw, Search as SearchIcon,
  ExternalLink, ChevronLeft, ChevronRight, X, Mail, Globe,
  Clock, Zap, ShieldAlert, Filter
} from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { supabase } from '../lib/supabase';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';

// ─── Helper: Build platform-specific job search URL ─────────────────────────
function buildJobSearchUrl(title: string, company: string, source: string, location?: string): string {
  // Strip AI-generated hash IDs like [#231046] from the title
  const cleanTitle = (title || '').replace(/\[#?\d+\]/g, '').trim();

  // Detect fake/placeholder company names generated by AI
  const fakeCompanyPattern = /^[A-Z]{2,4}\s+(Corporation|Industries|Services|Enterprises|Company|Technologies|Solutions|Group|Ltd)$/i;
  const isRealCompany = company && company.trim().length > 3 && !fakeCompanyPattern.test(company.trim().replace(/\s*\[#?\d+\]/, ''));

  // Build the core search query
  const cityPart = location ? location.split(',')[0].trim() : '';
  const searchTerms = [cleanTitle, isRealCompany ? company : ''].filter(Boolean).join(' ');
  const q = encodeURIComponent(searchTerms);
  const locQ = encodeURIComponent(cityPart || 'India');

  const src = (source || '').toLowerCase();

  // Platform-specific search URLs
  if (src.includes('linkedin'))  return `https://www.linkedin.com/jobs/search/?keywords=${q}&location=${locQ}`;
  if (src.includes('naukri'))    return `https://www.naukri.com/${cleanTitle.toLowerCase().replace(/\s+/g, '-')}-jobs-in-${(cityPart || 'india').toLowerCase().replace(/\s+/g, '-')}`;
  if (src.includes('indeed'))    return `https://in.indeed.com/jobs?q=${q}&l=${locQ}`;
  if (src.includes('glassdoor')) return `https://www.glassdoor.co.in/Job/jobs.htm?sc.keyword=${q}`;
  if (src.includes('monster'))   return `https://www.monster.com/jobs/search?q=${q}&where=${encodeURIComponent(cityPart || '')}`;
  if (src.includes('shine'))     return `https://www.shine.com/job-search/${cleanTitle.toLowerCase().replace(/\s+/g, '-')}-jobs`;

  // Default: LinkedIn Jobs
  return `https://www.linkedin.com/jobs/search/?keywords=${q}&location=${locQ}`;
}


// ─── Job Detail Drawer ───────────────────────────────────────────────────────
function JobDrawer({ match, onClose }: { match: any; onClose: () => void }) {
  const job = match?.jobs;
  if (!job) return null;

  const scoreColor = match.score >= 85 ? 'var(--accent)' : match.score >= 70 ? 'var(--primary)' : 'var(--warning)';
  const scoreBg   = match.score >= 85 ? 'var(--accent-glow)' : match.score >= 70 ? 'var(--primary-glow)' : 'rgba(210,153,34,0.15)';

  // Parse description into readable paragraphs
  const descParagraphs = (job.description || 'No description available.')
    .split(/\n{2,}|\.\s{2,}/)
    .filter((p: string) => p.trim().length > 20)
    .slice(0, 8);

  return (
    <>
      {/* Backdrop */}
      <div
        onClick={onClose}
        style={{
          position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.6)',
          backdropFilter: 'blur(4px)', zIndex: 200,
        }}
      />

      {/* Drawer panel */}
      <div style={{
        position: 'fixed', top: 0, right: 0, bottom: 0,
        width: 'min(540px, 100vw)',
        background: 'var(--surface)',
        borderLeft: '1px solid var(--border)',
        zIndex: 201,
        overflowY: 'auto',
        display: 'flex', flexDirection: 'column',
        boxShadow: '-8px 0 40px rgba(0,0,0,0.3)',
        animation: 'slideIn 0.22s ease',
      }}>
        <style>{`
          @keyframes slideIn { from { transform: translateX(100%); } to { transform: translateX(0); } }
        `}</style>

        {/* Header */}
        <div style={{
          padding: '1.5rem',
          borderBottom: '1px solid var(--border)',
          position: 'sticky', top: 0,
          background: 'var(--surface)', zIndex: 5,
        }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: '1rem' }}>
            <div style={{ minWidth: 0 }}>
              <h2 style={{ fontSize: '1.2rem', fontWeight: 800, lineHeight: 1.3, color: 'var(--text)' }}>
                {job.title}
              </h2>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.75rem', marginTop: '0.5rem', fontSize: '0.85rem', color: 'var(--text-muted)' }}>
                <span style={{ display: 'flex', alignItems: 'center', gap: '0.3rem' }}>
                  <Building size={14} /> {job.company || 'Unknown Company'}
                </span>
                {job.location && (
                  <span style={{ display: 'flex', alignItems: 'center', gap: '0.3rem' }}>
                    <MapPin size={14} /> {job.location}
                  </span>
                )}
              </div>
            </div>
            <button className="btn btn-ghost btn-icon" onClick={onClose} style={{ flexShrink: 0 }}>
              <X size={20} />
            </button>
          </div>

          {/* Score + badges */}
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem', marginTop: '1rem' }}>
            <span style={{ display: 'inline-flex', alignItems: 'center', gap: '0.35rem', padding: '0.35rem 0.875rem', borderRadius: 999, fontWeight: 700, fontSize: '0.9rem', background: scoreBg, color: scoreColor }}>
              <Star size={14} fill="currentColor" /> {match.score}% Match
            </span>
            {job.source && (
              <span className="badge badge-muted">
                <Globe size={11} /> {job.source}
              </span>
            )}
            {match.status === 'matched' && (
              <span className="badge badge-primary">
                <Zap size={11} /> Eligible for auto-apply
              </span>
            )}
            {job.is_flagged && (
              <span className="badge badge-error">
                <ShieldAlert size={11} /> Flagged suspicious
              </span>
            )}
          </div>
        </div>

        {/* Body */}
        <div style={{ padding: '1.5rem', flex: 1 }}>

          {/* Quick info grid */}
          {(job.apply_email || job.job_url || job.salary) && (
            <div style={{
              display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(160px, 1fr))',
              gap: '0.75rem', marginBottom: '1.5rem',
            }}>
              {job.apply_email && (
                <div style={{ padding: '0.875rem', background: 'var(--surface-alt)', borderRadius: 'var(--radius-md)', border: '1px solid var(--border)' }}>
                  <div style={{ fontSize: '0.7rem', fontWeight: 700, color: 'var(--text-subtle)', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: '0.35rem' }}>Apply Email</div>
                  <div style={{ fontSize: '0.82rem', color: 'var(--text)', wordBreak: 'break-all', display: 'flex', alignItems: 'flex-start', gap: '0.35rem' }}>
                    <Mail size={13} style={{ flexShrink: 0, marginTop: 2, color: 'var(--primary)' }} />
                    {job.apply_email}
                  </div>
                </div>
              )}
              {job.salary && (
                <div style={{ padding: '0.875rem', background: 'var(--surface-alt)', borderRadius: 'var(--radius-md)', border: '1px solid var(--border)' }}>
                  <div style={{ fontSize: '0.7rem', fontWeight: 700, color: 'var(--text-subtle)', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: '0.35rem' }}>Salary</div>
                  <div style={{ fontSize: '0.9rem', fontWeight: 700, color: 'var(--accent)' }}>{job.salary}</div>
                </div>
              )}
              {job.job_type && (
                <div style={{ padding: '0.875rem', background: 'var(--surface-alt)', borderRadius: 'var(--radius-md)', border: '1px solid var(--border)' }}>
                  <div style={{ fontSize: '0.7rem', fontWeight: 700, color: 'var(--text-subtle)', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: '0.35rem' }}>Job Type</div>
                  <div style={{ fontSize: '0.85rem', color: 'var(--text)', display: 'flex', alignItems: 'center', gap: '0.35rem' }}>
                    <Clock size={13} color="var(--primary)" /> {job.job_type}
                  </div>
                </div>
              )}
            </div>
          )}

          {/* Fraud warning */}
          {job.fraud_score > 40 && (
            <div style={{
              display: 'flex', gap: '0.75rem', padding: '0.875rem',
              background: 'rgba(248,81,73,0.08)', border: '1px solid rgba(248,81,73,0.25)',
              borderRadius: 'var(--radius-md)', marginBottom: '1.25rem',
              fontSize: '0.82rem', color: 'var(--error)', lineHeight: 1.5,
            }}>
              <ShieldAlert size={16} style={{ flexShrink: 0, marginTop: 2 }} />
              <div>
                <strong>Fraud Risk Score: {job.fraud_score}/100</strong> — Our AI flagged this job as potentially suspicious. Proceed with caution.
              </div>
            </div>
          )}

          {/* Description */}
          <div style={{ marginBottom: '1.5rem' }}>
            <div style={{ fontSize: '0.78rem', fontWeight: 700, color: 'var(--text-subtle)', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: '0.875rem' }}>
              Job Description
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
              {descParagraphs.length > 0 ? descParagraphs.map((para: string, i: number) => (
                <p key={i} style={{ fontSize: '0.875rem', color: 'var(--text-muted)', lineHeight: 1.75 }}>
                  {para.trim()}
                </p>
              )) : (
                <p style={{ fontSize: '0.875rem', color: 'var(--text-muted)', fontStyle: 'italic' }}>No detailed description available.</p>
              )}
            </div>
          </div>
        </div>

        {/* Footer actions */}
        <div style={{
          padding: '1.25rem 1.5rem',
          borderTop: '1px solid var(--border)',
          background: 'var(--surface)',
          position: 'sticky', bottom: 0,
          display: 'flex', gap: '0.75rem',
        }}>
          <a
            href={job.job_url || buildJobSearchUrl(job.title, job.company, job.source, job.location)}
            target="_blank"
            rel="noopener noreferrer"
            className="btn btn-primary"
            style={{ flex: 1, justifyContent: 'center' }}
          >
            <ExternalLink size={16} />
            {job.job_url ? 'Open Original Posting' : `Search on ${job.source || 'LinkedIn'}`}
          </a>
          <button className="btn btn-ghost" onClick={onClose}>Close</button>
        </div>
      </div>
    </>
  );
}

// ─── Main Jobs Page ──────────────────────────────────────────────────────────
export default function Jobs() {
  const { session } = useAuth();
  const userId = session?.user?.id;
  const [jobs, setJobs] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [selectedMatch, setSelectedMatch] = useState<any>(null);

  const [searchTerm, setSearchTerm] = useState('');
  const [sourceFilter, setSourceFilter] = useState('All');
  const [minMatchFilter, setMinMatchFilter] = useState('60');

  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 15;

  useEffect(() => { if (userId) fetchJobs(); }, [userId]);

  const fetchJobs = async () => {
    try {
      setLoading(true);
      const { data, error } = await supabase
        .from('job_matches')
        .select(`
          id, score, status,
          jobs (
            id, title, company, location, description,
            source, apply_email, job_url, salary, job_type,
            fraud_score, is_flagged
          )
        `)
        .eq('user_id', userId)
        .gte('score', 60)
        .order('score', { ascending: false });

      if (error) throw error;
      setJobs(data || []);
    } catch (error) {
      console.error('Failed to fetch matched jobs', error);
    } finally {
      setLoading(false);
    }
  };

  const triggerFinder = async () => {
    try {
      await axios.post(`${API_URL}/jobs/trigger-finder`);
      alert('Job Finder triggered! New jobs will appear in a moment.');
      setTimeout(fetchJobs, 8000);
    } catch {
      alert('Failed to trigger job finder.');
    }
  };

  const filteredJobs = jobs.filter(match => {
    const job = match.jobs;
    if (!job) return false;
    if (sourceFilter !== 'All' && job.source !== sourceFilter) return false;
    if (match.score < parseInt(minMatchFilter)) return false;
    if (searchTerm) {
      const t = searchTerm.toLowerCase();
      return job.title?.toLowerCase().includes(t) || job.company?.toLowerCase().includes(t);
    }
    return true;
  });

  const totalPages = Math.ceil(filteredJobs.length / itemsPerPage);
  const paginatedJobs = filteredJobs.slice((currentPage - 1) * itemsPerPage, currentPage * itemsPerPage);

  const scoreColor = (s: number) => s >= 85 ? 'var(--accent)' : s >= 70 ? 'var(--primary)' : 'var(--warning)';
  const scoreBg    = (s: number) => s >= 85 ? 'var(--accent-glow)' : s >= 70 ? 'var(--primary-glow)' : 'rgba(210,153,34,0.15)';

  return (
    <div>
      {/* Header */}
      <div className="page-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '1rem' }}>
        <div>
          <h2>Matched Jobs</h2>
          <p>{filteredJobs.length} jobs matching your extracted profile</p>
        </div>
        <button className="btn btn-outline" onClick={triggerFinder} disabled={loading}>
          <RefreshCw size={16} className={loading ? 'spinning' : ''} /> Find New Jobs
        </button>
      </div>

      {/* Filters */}
      <div style={{ display: 'flex', gap: '0.75rem', marginBottom: '1.5rem', flexWrap: 'wrap' }}>
        <div style={{ flex: '1 1 200px', position: 'relative' }}>
          <SearchIcon size={16} style={{ position: 'absolute', left: '0.875rem', top: '50%', transform: 'translateY(-50%)', color: 'var(--text-subtle)', pointerEvents: 'none' }} />
          <input
            type="text"
            placeholder="Search by title or company…"
            className="form-control"
            style={{ paddingLeft: '2.4rem' }}
            value={searchTerm}
            onChange={e => { setSearchTerm(e.target.value); setCurrentPage(1); }}
          />
        </div>
        <div style={{ position: 'relative' }}>
          <Filter size={14} style={{ position: 'absolute', left: '0.8rem', top: '50%', transform: 'translateY(-50%)', color: 'var(--text-subtle)', pointerEvents: 'none' }} />
          <select className="form-control" style={{ paddingLeft: '2.2rem', minWidth: 150, cursor: 'pointer' }} value={sourceFilter} onChange={e => { setSourceFilter(e.target.value); setCurrentPage(1); }}>
            <option value="All">All Platforms</option>
            <option value="LinkedIn">LinkedIn</option>
            <option value="Indeed">Indeed</option>
            <option value="Glassdoor">Glassdoor</option>
            <option value="Monster">Monster</option>
            <option value="Naukri">Naukri</option>
          </select>
        </div>
        <select className="form-control" style={{ minWidth: 145, cursor: 'pointer' }} value={minMatchFilter} onChange={e => { setMinMatchFilter(e.target.value); setCurrentPage(1); }}>
          <option value="60">All Matches</option>
          <option value="75">75%+ Match</option>
          <option value="85">85%+ Match</option>
          <option value="95">95%+ Match</option>
        </select>
      </div>

      {/* Job Cards */}
      {loading ? (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
          {[1, 2, 3, 4, 5].map(i => (
            <div key={i} className="skeleton" style={{ height: 110, borderRadius: 'var(--radius-lg)' }} />
          ))}
        </div>
      ) : paginatedJobs.length === 0 ? (
        <div className="empty-state">
          <div className="empty-state-icon">🔍</div>
          <p style={{ fontWeight: 600, fontSize: '1rem', color: 'var(--text)' }}>No jobs found</p>
          <p style={{ fontSize: '0.875rem', marginTop: '0.35rem' }}>
            {jobs.length === 0 ? 'Make sure your profile is complete, then click "Find New Jobs".' : 'Try adjusting your filters.'}
          </p>
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
          {paginatedJobs.map((match) => {
            const job = match.jobs;
            return (
              <div
                key={match.id}
                className="card"
                style={{ cursor: 'pointer', transition: 'var(--transition)' }}
                onClick={() => setSelectedMatch(match)}
              >
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: '1rem' }}>
                  {/* Job info */}
                  <div style={{ minWidth: 0, flex: 1 }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', flexWrap: 'wrap' }}>
                      <h3 style={{ fontSize: '1rem', fontWeight: 700, color: 'var(--text)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                        {job?.title}
                      </h3>
                      {job?.is_flagged && (
                        <span className="badge badge-error" style={{ fontSize: '0.68rem' }}><ShieldAlert size={10} /> Suspicious</span>
                      )}
                    </div>
                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.75rem', marginTop: '0.35rem', fontSize: '0.82rem', color: 'var(--text-muted)' }}>
                      <span style={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                        <Building size={13} /> {job?.company}
                      </span>
                      {job?.location && (
                        <span style={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                          <MapPin size={13} /> {job?.location}
                        </span>
                      )}
                      {job?.source && (
                        <span style={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                          <Globe size={13} /> {job?.source}
                        </span>
                      )}
                    </div>
                    {/* Description preview */}
                    <p style={{ fontSize: '0.82rem', color: 'var(--text-subtle)', marginTop: '0.5rem', lineHeight: 1.5, display: '-webkit-box', WebkitLineClamp: 2, WebkitBoxOrient: 'vertical', overflow: 'hidden' }}>
                      {job?.description?.substring(0, 180)}…
                    </p>
                  </div>

                  {/* Score badge */}
                  <div style={{ flexShrink: 0 }}>
                    <span style={{
                      display: 'inline-flex', alignItems: 'center', gap: '0.3rem',
                      padding: '0.3rem 0.7rem', borderRadius: 999,
                      background: scoreBg(match.score), color: scoreColor(match.score),
                      fontWeight: 700, fontSize: '0.85rem',
                    }}>
                      <Star size={13} fill="currentColor" /> {match.score}%
                    </span>
                  </div>
                </div>

                {/* Card footer: action buttons */}
                <div
                  style={{
                    display: 'flex', gap: '0.5rem', paddingTop: '0.875rem',
                    borderTop: '1px solid var(--border)', marginTop: '0.25rem',
                  }}
                  onClick={e => e.stopPropagation()} // prevent row click
                >
                  <a
                    href={job?.job_url || buildJobSearchUrl(job?.title, job?.company, job?.source, job?.location)}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="btn btn-primary"
                    style={{ flex: 1, justifyContent: 'center', fontSize: '0.83rem', padding: '0.5rem 0.75rem' }}
                  >
                    <ExternalLink size={14} />
                    View on {job?.source || 'LinkedIn'}
                  </a>
                  <button
                    className="btn btn-outline"
                    style={{ fontSize: '0.83rem', padding: '0.5rem 0.875rem' }}
                    onClick={() => setSelectedMatch(match)}
                  >
                    Details
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Pagination */}
      {totalPages > 1 && !loading && (
        <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '1rem', marginTop: '2rem' }}>
          <button className="btn btn-outline" disabled={currentPage === 1} onClick={() => setCurrentPage(p => p - 1)}>
            <ChevronLeft size={16} /> Prev
          </button>
          <span style={{ fontSize: '0.875rem', color: 'var(--text-muted)' }}>
            {currentPage} / {totalPages}
          </span>
          <button className="btn btn-outline" disabled={currentPage === totalPages} onClick={() => setCurrentPage(p => p + 1)}>
            Next <ChevronRight size={16} />
          </button>
        </div>
      )}

      {/* Job Detail Drawer */}
      {selectedMatch && (
        <JobDrawer match={selectedMatch} onClose={() => setSelectedMatch(null)} />
      )}
    </div>
  );
}
